apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: starbucks-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: starbucks-app   
  endpoints:
  - port: http
    interval: 15s